name: Run Cypress tests on upload

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Make repo available
        uses: actions/checkout@v2

      - name: Cypress run all
        uses: cypress-io/github-action@v3
        with:
          project: ./
          browser: chrome
